name: flutter_login_auth
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true